import Head from 'next/head'
import { Button, Code, Image } from '@chakra-ui/react'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import axios from "axios"
import Link from 'next/link'
import {useRouter} from "next/router"
import {TbGitFork} from "react-icons/tb"
import {AiOutlineStar} from "react-icons/ai"



const inter = Inter({ subsets: ['latin'] })

export default function Home({data,repo}) {
  console.log(repo);
  const route=useRouter()
  const handleclick=(id)=>{
    route.push(id)
  }
  return (
    <>
      <Head>
        <title>R Giri Reddy Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='parent'>
          <div className="left">
              <div className="l-top">
                  <Image src={data.avatar_url}></Image>
                  <h1 style={{fontSize:"20px",color:"yellow"}}>{data.name}</h1>
                  <p>{data.company}</p>
                  <h2 style={{marginTop:"3%"}}>{data.bio}</h2>
                  <div style={{margin:"3% 0"}}>
                    <p style={{display:"inline"}}>Followers:{data.followers}</p>
                    <p style={{display:"inline",marginLeft:"10px"}}>Following:{data.following}</p>
                  </div>
                  <div style={{display:"flex",width:"100%",justifyContent:"space-between",marginTop:"2%"}}>
                 <Link target="_blank" href="https://drive.google.com/file/d/18Lv83gxFAq4d4EWxGFproS_ju1DTpYey/view?usp=share_link"> <Button colorScheme="pink">Resume</Button></Link> 
                 <Link target="_blank" href={data.html_url}><Button colorScheme="blue">Follow</Button></Link> 
                 </div>

                
              </div>
              <div className="l-mid">
                  <Code colorScheme="purple" className='tech' >HTML</Code>
                  <Code colorScheme="purple" className='tech'>CSS</Code>
                  <Code colorScheme="purple" className='tech'>JAVASCRIPT</Code>
                  <Code colorScheme="purple" className='tech'>REACT</Code>
                  <Code colorScheme="purple" className='tech'>REDUX</Code>
                  <Code colorScheme="purple" className='tech'>NEXT.JS</Code>
                  <Code colorScheme="purple" className='tech'>TYPESCRIPT</Code>
                  <Code colorScheme="purple" className='tech'>NODE.JS</Code>
                  <Code colorScheme="purple" className='tech'>CHAKRA-UI</Code>
                  <Code colorScheme="purple" className='tech'>MONGODB</Code>
              </div>
              <div className="l-bot">
                  <h1>FULL STACK WEB DEVELOPMENT </h1>
                  <p> MASAI SCHOOL</p>
                  <p>JUL 2022- PRESENT</p>
                  <h1>POST Graduation In ARTS</h1>
                  <p>BINAYAK ACHARYA COLLEGE</p>
                  <p>2018-2021</p>
              </div>
          </div>
          <div className="right">
              {
                repo.items.map((ele,ind)=>{
                    return(
                      <div  style={{display:"flex",flexDirection:"column",justifyContent:"space-between"}} key={ind} onClick={()=>handleclick(ele.html_url)}>
                      <div>
                        <h1 className='repos'>{ele.name}</h1>
                        <p>{ele.description}</p>
                        </div>
                    <div style={{display:"flex",justifyContent:"space-between",marginTop:"5%",height:"auto"}}>
                      <div style={{display:"flex",gap:"10px"}} >
                        <TbGitFork/>
                        {ele.forks_count}
                        <AiOutlineStar/>
                        {ele.stargazers_count}
                        </div>
                        <div>
                         <h1> {ele.language}</h1>
                        </div>
                      </div>
                      </div>
                    )
                })
              }
          </div>
      </div>
    </>
  )
}
export async function getServerSideProps(context){
  let res=await axios.get("https://api.github.com/users/geraltyen")
  let res2=await axios.get("https://api.github.com/search/repositories?q=user:geraltyen+fork:true&sort=updated&per_page=10&type=Repositories")
  return{
    props:{
      data:res.data,
      repo:res2.data
    }
  }
}
